language: objective-c
osx_image: xcode8.2

before_install:
- xcrun simctl delete AD8E8C76-910E-437D-88C2-4D6F6EBE3355

script:
- xcodebuild clean build -sdk iphonesimulator -workspace DnDice.xcworkspace -scheme DnDice CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.2' test